version: "3"

services:
  upstat_backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env # Specify the path to the .env file for the app service
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
